[book]
authors = ["nasuf"]
language = "en"
multilingual = false
src = "src"
title = "NASUF Dev Notes"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/nasuf/nasuf.github.io/tree/main/src"
git-repository-icon = "fa-github"
